---
output: 
  html_document:
    number_sections: false
    toc: no
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE
)
```

# Slides

## Research overview

General introduction to my current research: [HTML](https://slides.jhelvy.com/helveston-research), [PDF](https://github.com/jhelvy/slides/raw/main/helveston-research/helveston-research.pdf)

## Talks 

Slides for various talks:

```{r, echo=FALSE}
library(knitr)
library(dplyr)
library(kableExtra)

readr::read_csv('slides.csv') %>%
    mutate(
        slides = paste0(
            '[', stub,  '](https://slides.jhelvy.com/', stub, ')'),
        pdf = paste0(
            '[PDF](https://github.com/jhelvy/slides/raw/main/',
            stub, '/', stub, '.pdf)'),
        slides = ifelse(
            !is.na(link), 
            paste0('[', stub,  '](', link, ')'), 
            slides
        ),
        pdf = ifelse(!is.na(link), '', pdf)
    ) %>%
    select(-stub, -link) %>%
    janitor::clean_names(case = 'title') %>%
    rename(PDF = Pdf) %>%
    kbl() %>%
     kable_styling(bootstrap_options = c(
         "striped", "hover", "condensed")) %>%
    column_spec(column = 1, width = '8em') %>%
    column_spec(column = 2, width = '25em') %>%
    column_spec(column = 3, width = '25em') %>%
    column_spec(column = 4, width = '8em') %>%
    column_spec(column = 5, width = '15em')
```
