on:
  push:
    branches: [main, master]

name: Render & Deploy index.html

jobs:
  build:
    runs-on: macOS-10.15
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages('rmarkdown')
          install.packages('markdown')
          install.packages('htmltools')
        shell: Rscript {0}

      - name: Render index.html
        run: |
          rmarkdown::render("index.Rmd")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git commit index.html -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"